# Website settings
baseurl: "" # should not include hostname

# Internal nav
nav:
  main:
    posts: "/posts"
    projects: "/projects"
  posts:
    all: "/posts"
    popular: "/posts/popular"
    tags: "/posts/tags"
    rss: "/feed.xml"

# Bio settings
name: "David Dearing"
description: "The home page of David Dearing, AI Software Engineer."
#thumbnail_path: "dpdearing-medium.jpg"
website_repo_url: "https://github.com/dpdearing/dpdearing-homepage"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/dpdearing"
    label: "Twitter"
    icon: "twitter-square"
    username: "@dpdearing"
  github:
    url: "https://github.com/dpdearing"
    label: "GitHub"
    icon: "github-square"

# Jekyll build settings
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "/posts/page:num"
permalink: "/posts/:year/:month/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: dpdearing/dpdearing-homepage

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
