# Website settings
baseurl: "/"

# Internal nav
nav:
  main:
    writing: "/writing"
    projects: "/projects"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "David Dearing"
description: "The home page of David Dearing, AI Software Engineer."
#thumbnail_path: "dpdearing-medium.jpg"
website_repo_url: "https://github.com/dpdearing/dpdearing-homepage"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/dpdearing"
    label: "Twitter"
    icon: "twitter-square"
    username: "@dpdearing"
  github:
    url: "https://github.com/dpdearing"
    label: "GitHub"
    icon: "github-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: dpdearing/dpdearing-homepage

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
